version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
        - ./data/db:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=wp
        - MYSQL_DATABASE=wp
        - MYSQL_USER=wp
        - MYSQL_PASSWORD=wp
        
    wp:
        build: .
        volumes:
        - ./data/wp:/var/www/html
        environment:
        - WORDPRESS_DB_HOST=db
        - WORDPRESS_DB_USER=wp
        - WORDPRESS_DB_PASSWORD=wp
        - WORDPRESS_DB_NAME=wp
        - |
          WORDPRESS_CONFIG_EXTRA=
          define ( 'WP_SITEURL', 'http://localhost:8000/subfolder' );
          define ( 'WP_HOME', 'http://localhost:8000/subfolder' );
          define ( 'WP_MEMORY_LIMIT', '32M' );

    traefik:
        image: traefik
        ports:
        - 8000:8000
        volumes:
        - ./traefik:/etc/traefik
